fix: continuous_backup_config issue for failover replica
GoogleCloudPlatform/terraform-google-alloy-db pull request #72
Opened 2024-03-08 05:54 UTC by imrannayer

Fixed error noticed in PR #71

2024-03-09 05:54 UTC, g-awmalik commented on examples/simple_example/cross_region_replica.tf
> +module "alloydb2" {
Please replace the module name with something more meaningful.

2024-03-09 05:56 UTC, g-awmalik requested changes
Thanks for the PR. I'm good with most of the configuration except where you have variables or modules named as `alloydb1`, `region1` etc. Please replace them with more meaningful names.

2024-03-11 19:08 UTC, imrannayer commented
@imrannayer applied changes. Plz review?

2024-03-25 20:47 UTC, g-awmalik approved these changes

2024-03-25 21:13 UTC, merged